nelmio_api_doc:
    documentation:
        info:
            title: Bilemo API
            description: The Bilemo API for developers - by Mathieu Delclos
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []

    areas:
        path_patterns:
            - ^/api/products
            - ^/api/users

    models:
        names:
            - { alias: Products list,   type: App\Entity\Product, groups: [ products_list ] }
            - { alias: Product details, type: App\Entity\Product, groups: [ product_details ] }
            - { alias: Users list,      type: App\Entity\User,    groups: [ users_list ] }
            - { alias: User details,    type: App\Entity\User,    groups: [ user_details ] }